### ISSUE TITLE
Add `fieldset` and `legend` support

### ISSUE THREAD

**Issue by wavebeem** [wavebeem/1bit-ui#17]
Something approximately like this:

```css
fieldset {
  border: var(--bit-border-width) solid var(--bit-color0);
  padding: 1rem;
  padding-top: 0.5rem;
  margin: 0;
}

legend {
  padding: 0 0.5rem;
  margin: 0;
}
```
